"""initial greenflex schema

Revision ID: f59417dcb05c
Revises:
Create Date: 2026-07-19 16:44:46.820898
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "f59417dcb05c"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "audit_events",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("entity_type", sa.String(length=32), nullable=False),
        sa.Column("entity_id", sa.String(length=36), nullable=False),
        sa.Column("event_type", sa.String(length=64), nullable=False),
        sa.Column("metadata_json", sa.Text(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_audit_entity", "audit_events", ["entity_type", "entity_id"], unique=False)
    op.create_table(
        "model_catalog",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("runtime_name", sa.String(length=128), nullable=False),
        sa.Column("display_name", sa.String(length=128), nullable=False),
        sa.Column("tier", sa.String(length=24), nullable=False),
        sa.Column("parameter_b", sa.String(length=16), nullable=False),
        sa.Column("context_limit", sa.Integer(), nullable=False),
        sa.Column("recommended_for_json", sa.Text(), nullable=False),
        sa.Column("input_rate_micro_rmb_per_million", sa.Integer(), nullable=False),
        sa.Column("output_rate_micro_rmb_per_million", sa.Integer(), nullable=False),
        sa.Column("estimated_tokens_per_second", sa.Integer(), nullable=False),
        sa.Column("estimated_energy_micro_wh_per_1k_output", sa.Integer(), nullable=False),
        sa.Column("digest", sa.String(length=128), nullable=True),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("runtime_name"),
    )
    op.create_index(op.f("ix_model_catalog_tier"), "model_catalog", ["tier"], unique=False)
    op.create_table(
        "quotes",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("tenant_id", sa.String(length=64), nullable=False),
        sa.Column("model_id", sa.String(length=64), nullable=False),
        sa.Column("execution_mode", sa.String(length=24), nullable=False),
        sa.Column("item_count", sa.Integer(), nullable=False),
        sa.Column("input_tokens_est", sa.Integer(), nullable=False),
        sa.Column("output_tokens_est", sa.Integer(), nullable=False),
        sa.Column("content_json", sa.Text(), nullable=False),
        sa.Column("scheduled_start", sa.DateTime(timezone=True), nullable=False),
        sa.Column("scheduled_end", sa.DateTime(timezone=True), nullable=False),
        sa.Column("deadline", sa.DateTime(timezone=True), nullable=True),
        sa.Column("base_price_micro_rmb", sa.Integer(), nullable=False),
        sa.Column("discount_bps", sa.Integer(), nullable=False),
        sa.Column("discount_micro_rmb", sa.Integer(), nullable=False),
        sa.Column("vpp_rebate_micro_rmb", sa.Integer(), nullable=False),
        sa.Column("total_price_micro_rmb", sa.Integer(), nullable=False),
        sa.Column("facility_energy_micro_wh_est", sa.Integer(), nullable=False),
        sa.Column("carbon_micro_g_est", sa.Integer(), nullable=False),
        sa.Column("renewable_share_bps", sa.Integer(), nullable=False),
        sa.Column("signal_version", sa.String(length=64), nullable=False),
        sa.Column("pricing_version", sa.String(length=64), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["model_id"],
            ["model_catalog.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_quotes_expires_at"), "quotes", ["expires_at"], unique=False)
    op.create_index(op.f("ix_quotes_tenant_id"), "quotes", ["tenant_id"], unique=False)
    op.create_table(
        "orders",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("tenant_id", sa.String(length=64), nullable=False),
        sa.Column("quote_id", sa.String(length=36), nullable=False),
        sa.Column("model_id", sa.String(length=64), nullable=False),
        sa.Column("execution_mode", sa.String(length=24), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("scheduled_start", sa.DateTime(timezone=True), nullable=False),
        sa.Column("deadline", sa.DateTime(timezone=True), nullable=True),
        sa.Column("quoted_price_micro_rmb", sa.Integer(), nullable=False),
        sa.Column("actual_price_micro_rmb", sa.Integer(), nullable=True),
        sa.Column("gross_gpu_energy_micro_wh", sa.Integer(), nullable=True),
        sa.Column("incremental_gpu_energy_micro_wh", sa.Integer(), nullable=True),
        sa.Column("facility_energy_micro_wh", sa.Integer(), nullable=True),
        sa.Column("location_carbon_micro_g", sa.Integer(), nullable=True),
        sa.Column("content_purged", sa.Boolean(), nullable=False),
        sa.Column("lease_owner", sa.String(length=64), nullable=True),
        sa.Column("lease_expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["model_id"],
            ["model_catalog.id"],
        ),
        sa.ForeignKeyConstraint(
            ["quote_id"],
            ["quotes.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("quote_id", name="uq_orders_quote_id"),
    )
    op.create_index(op.f("ix_orders_scheduled_start"), "orders", ["scheduled_start"], unique=False)
    op.create_index(op.f("ix_orders_status"), "orders", ["status"], unique=False)
    op.create_index(op.f("ix_orders_tenant_id"), "orders", ["tenant_id"], unique=False)
    op.create_table(
        "executions",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("order_id", sa.String(length=36), nullable=False),
        sa.Column("telemetry_source", sa.String(length=64), nullable=False),
        sa.Column("telemetry_provenance", sa.String(length=24), nullable=False),
        sa.Column("idle_power_mw", sa.Integer(), nullable=True),
        sa.Column("average_power_mw", sa.Integer(), nullable=True),
        sa.Column("peak_power_mw", sa.Integer(), nullable=True),
        sa.Column("sample_count", sa.Integer(), nullable=False),
        sa.Column("raw_artifact_path", sa.String(length=512), nullable=True),
        sa.Column("raw_artifact_sha256", sa.String(length=64), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["order_id"],
            ["orders.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("order_id"),
    )
    op.create_table(
        "order_items",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("order_id", sa.String(length=36), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("client_item_id", sa.String(length=128), nullable=False),
        sa.Column("prompt", sa.Text(), nullable=True),
        sa.Column("system_prompt", sa.Text(), nullable=True),
        sa.Column("max_output_tokens", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=24), nullable=False),
        sa.Column("output", sa.Text(), nullable=True),
        sa.Column("prompt_tokens", sa.Integer(), nullable=True),
        sa.Column("output_tokens", sa.Integer(), nullable=True),
        sa.Column("duration_us", sa.Integer(), nullable=True),
        sa.Column("error_code", sa.String(length=64), nullable=True),
        sa.ForeignKeyConstraint(["order_id"], ["orders.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("order_id", "client_item_id", name="uq_order_client_item"),
    )
    op.create_index(
        "ix_order_items_order_status", "order_items", ["order_id", "status"], unique=False
    )
    op.create_table(
        "passports",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("order_id", sa.String(length=36), nullable=False),
        sa.Column("payload_json", sa.Text(), nullable=False),
        sa.Column("payload_sha256", sa.String(length=64), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["order_id"],
            ["orders.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("order_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("passports")
    op.drop_index("ix_order_items_order_status", table_name="order_items")
    op.drop_table("order_items")
    op.drop_table("executions")
    op.drop_index(op.f("ix_orders_tenant_id"), table_name="orders")
    op.drop_index(op.f("ix_orders_status"), table_name="orders")
    op.drop_index(op.f("ix_orders_scheduled_start"), table_name="orders")
    op.drop_table("orders")
    op.drop_index(op.f("ix_quotes_tenant_id"), table_name="quotes")
    op.drop_index(op.f("ix_quotes_expires_at"), table_name="quotes")
    op.drop_table("quotes")
    op.drop_index(op.f("ix_model_catalog_tier"), table_name="model_catalog")
    op.drop_table("model_catalog")
    op.drop_index("ix_audit_entity", table_name="audit_events")
    op.drop_table("audit_events")
    # ### end Alembic commands ###
