/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/models": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Models */
        get: operations["models_api_v1_models_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/previews": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Previews */
        post: operations["previews_api_v1_previews_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/quotes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Quotes */
        post: operations["quotes_api_v1_quotes_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/quotes/upload": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Upload Quote */
        post: operations["upload_quote_api_v1_quotes_upload_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/orders": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Orders List */
        get: operations["orders_list_api_v1_orders_get"];
        put?: never;
        /** Orders Create */
        post: operations["orders_create_api_v1_orders_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/orders/{order_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Orders Get */
        get: operations["orders_get_api_v1_orders__order_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/orders/{order_id}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Orders Cancel */
        post: operations["orders_cancel_api_v1_orders__order_id__cancel_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/orders/{order_id}/content": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Orders Purge */
        delete: operations["orders_purge_api_v1_orders__order_id__content_delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/orders/{order_id}/results": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Orders Results */
        get: operations["orders_results_api_v1_orders__order_id__results_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/passports/{passport_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Passports Get */
        get: operations["passports_get_api_v1_passports__passport_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/orders/{order_id}/passport": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Passport By Order */
        get: operations["passport_by_order_api_v1_orders__order_id__passport_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health/live": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Live */
        get: operations["live_health_live_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Ready */
        get: operations["ready_health_ready_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** BatchItemInput */
        BatchItemInput: {
            /** Client Item Id */
            client_item_id: string;
            /** Prompt */
            prompt: string;
            /** System Prompt */
            system_prompt?: string | null;
            /**
             * Max Output Tokens
             * @default 256
             */
            max_output_tokens: number;
        };
        /** Body_upload_quote_api_v1_quotes_upload_post */
        Body_upload_quote_api_v1_quotes_upload_post: {
            /** File */
            file: string;
            /** Model Id */
            model_id?: string | null;
            tier?: components["schemas"]["ModelTier"] | null;
            /** Deadline */
            deadline?: string | null;
        };
        /** CreateOrderRequest */
        CreateOrderRequest: {
            /** Quote Id */
            quote_id: string;
        };
        /**
         * ExecutionMode
         * @enum {string}
         */
        ExecutionMode: "immediate" | "flexible";
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * ItemStatus
         * @enum {string}
         */
        ItemStatus: "pending" | "running" | "succeeded" | "failed";
        /** ModelCatalogItem */
        ModelCatalogItem: {
            /** Id */
            id: string;
            /** Display Name */
            display_name: string;
            /** Runtime Name */
            runtime_name: string;
            tier: components["schemas"]["ModelTier"];
            /** Parameter B */
            parameter_b: string;
            /** Context Limit */
            context_limit: number;
            /** Recommended For */
            recommended_for: string[];
            /** Input Rate Rmb Per Million */
            input_rate_rmb_per_million: string;
            /** Output Rate Rmb Per Million */
            output_rate_rmb_per_million: string;
            /** Available */
            available: boolean;
            /** Availability Detail */
            availability_detail: string;
            /** @default simulated */
            rate_provenance: components["schemas"]["Provenance"];
        };
        /**
         * ModelTier
         * @enum {string}
         */
        ModelTier: "economy" | "balanced" | "quality";
        /** OrderItemView */
        OrderItemView: {
            /** Client Item Id */
            client_item_id: string;
            status: components["schemas"]["ItemStatus"];
            /** Output */
            output: string | null;
            /** Prompt Tokens */
            prompt_tokens: number | null;
            /** Output Tokens */
            output_tokens: number | null;
            /** Duration Ms */
            duration_ms: string | null;
            /** Error Code */
            error_code: string | null;
        };
        /**
         * OrderStatus
         * @enum {string}
         */
        OrderStatus: "queued" | "scheduled" | "running" | "succeeded" | "partial_success" | "failed" | "cancelled";
        /** OrderView */
        OrderView: {
            /** Id */
            id: string;
            /** Quote Id */
            quote_id: string;
            /** Model Id */
            model_id: string;
            /** Model Name */
            model_name: string;
            execution_mode: components["schemas"]["ExecutionMode"];
            status: components["schemas"]["OrderStatus"];
            /**
             * Scheduled Start
             * Format: date-time
             */
            scheduled_start: string;
            /** Deadline */
            deadline: string | null;
            /** Quoted Price Rmb */
            quoted_price_rmb: string;
            /** Actual Price Rmb */
            actual_price_rmb: string | null;
            /** Item Count */
            item_count: number;
            /** Succeeded Count */
            succeeded_count: number;
            /** Failed Count */
            failed_count: number;
            /** Gross Gpu Energy Wh */
            gross_gpu_energy_wh: string | null;
            /** Incremental Gpu Energy Wh */
            incremental_gpu_energy_wh: string | null;
            /** Location Carbon G */
            location_carbon_g: string | null;
            /** Content Purged */
            content_purged: boolean;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Started At */
            started_at: string | null;
            /** Completed At */
            completed_at: string | null;
            /** Items */
            items?: components["schemas"]["OrderItemView"][] | null;
        };
        /** PassportView */
        PassportView: {
            /** Passport Id */
            passport_id: string;
            /** Order Id */
            order_id: string;
            /** Payload Sha256 */
            payload_sha256: string;
            /** Payload */
            payload: {
                [key: string]: unknown;
            };
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** PreviewRequest */
        PreviewRequest: {
            /** Model Id */
            model_id: string;
            /** Prompt */
            prompt: string;
            /** System Prompt */
            system_prompt?: string | null;
            /**
             * Max Output Tokens
             * @default 256
             */
            max_output_tokens: number;
        };
        /** PreviewResponse */
        PreviewResponse: {
            /** Model Id */
            model_id: string;
            /** Output */
            output: string;
            /** Prompt Tokens */
            prompt_tokens: number;
            /** Output Tokens */
            output_tokens: number;
            /** Latency Ms */
            latency_ms: string;
            /** Gross Gpu Energy Wh */
            gross_gpu_energy_wh: string | null;
            /** Incremental Gpu Energy Wh */
            incremental_gpu_energy_wh: string | null;
            telemetry_provenance: components["schemas"]["Provenance"];
            /** Telemetry Source */
            telemetry_source: string;
        };
        /**
         * Provenance
         * @enum {string}
         */
        Provenance: "measured" | "estimated" | "simulated";
        /** QuoteOption */
        QuoteOption: {
            /** Quote Id */
            quote_id: string;
            /** Model Id */
            model_id: string;
            /** Model Name */
            model_name: string;
            tier: components["schemas"]["ModelTier"];
            execution_mode: components["schemas"]["ExecutionMode"];
            /** Item Count */
            item_count: number;
            /** Estimated Input Tokens */
            estimated_input_tokens: number;
            /** Estimated Output Tokens */
            estimated_output_tokens: number;
            /**
             * Scheduled Start
             * Format: date-time
             */
            scheduled_start: string;
            /**
             * Scheduled End
             * Format: date-time
             */
            scheduled_end: string;
            /** Deadline */
            deadline: string | null;
            /** Base Price Rmb */
            base_price_rmb: string;
            /** Discount Percent */
            discount_percent: string;
            /** Discount Rmb */
            discount_rmb: string;
            /** Vpp Rebate Rmb */
            vpp_rebate_rmb: string;
            /** Total Price Rmb */
            total_price_rmb: string;
            /** Facility Energy Wh Est */
            facility_energy_wh_est: string;
            /** Carbon G Est */
            carbon_g_est: string;
            /** Renewable Share Percent */
            renewable_share_percent: string;
            /** Pricing Version */
            pricing_version: string;
            /** Signal Version */
            signal_version: string;
            /** @default simulated */
            commercial_provenance: components["schemas"]["Provenance"];
            /** @default simulated */
            environmental_provenance: components["schemas"]["Provenance"];
            /**
             * Expires At
             * Format: date-time
             */
            expires_at: string;
        };
        /** QuoteRequest */
        QuoteRequest: {
            /** Items */
            items: components["schemas"]["BatchItemInput"][];
            /** Model Id */
            model_id?: string | null;
            tier?: components["schemas"]["ModelTier"] | null;
            /** Deadline */
            deadline?: string | null;
        };
        /** QuoteResponse */
        QuoteResponse: {
            /** Options */
            options: components["schemas"]["QuoteOption"][];
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    models_api_v1_models_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ModelCatalogItem"][];
                };
            };
        };
    };
    previews_api_v1_previews_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PreviewRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PreviewResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    quotes_api_v1_quotes_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["QuoteRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QuoteResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    upload_quote_api_v1_quotes_upload_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_upload_quote_api_v1_quotes_upload_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QuoteResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    orders_list_api_v1_orders_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrderView"][];
                };
            };
        };
    };
    orders_create_api_v1_orders_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateOrderRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrderView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    orders_get_api_v1_orders__order_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                order_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrderView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    orders_cancel_api_v1_orders__order_id__cancel_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                order_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrderView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    orders_purge_api_v1_orders__order_id__content_delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                order_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrderView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    orders_results_api_v1_orders__order_id__results_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                order_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    passports_get_api_v1_passports__passport_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                passport_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PassportView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    passport_by_order_api_v1_orders__order_id__passport_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                order_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PassportView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    live_health_live_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    ready_health_ready_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
}
